### ISSUE TITLE
Not able to open exported xslx file with EXCEL

### ISSUE THREAD

**Issue by ThoreKleinschmidt** [pinussilvestrus/camunda-modeler-excel-import-plugin#106]
__Describe the Bug__

EXCEL is not able to open a file which was exported via the plugin from a DMN table created with Camunda modeler. 

__Steps to Reproduce__

1. Create the DMN or load an existing one into the Modeler
2. Export via plugin as xlsx file
3. Open EXCEL
4. Select exported xslx file to open
5. Excel opens popup "Problems occured. Should we restore the  content as much as possible..."
6. Click on YES
7. Another popup appears "EXCEL cannnot open the file *.* ..."

__Expected Behavior__

EXCEL should open the exported file.

__Environment__

- OS: Windows 10 64-bit
- Camunda Modeler 5.0.0
- Plugin Version: 1.3.1
- EXCEL Version 2108 (Office 365)

[DMN_Export.zip](https://github.com/pinussilvestrus/camunda-modeler-excel-import-plugin/files/9085140/DMN_Export.zip)

**Comment by pinussilvestrus** [comment]
Thank you for reporting! I can reproduce this on Windows with the latest version of the plugin. I will investigate this 👍

**Comment by pinussilvestrus** [comment]
The issue should be resolved via https://github.com/pinussilvestrus/camunda-modeler-excel-import-plugin/commit/586c1a9bff94dc22f81773aac69243fba5b8ecd6. I had to pin the `node-xlsx` which handles the Excel export. For some reason, it behaves differently in newer versions of the library. 

You can use the latest plugin version of the `main` branch. Feel free to reach out if something is still not working 👍
