### ISSUE TITLE
Add support for C8 DMN

### ISSUE THREAD

**Issue by pinussilvestrus** [pinussilvestrus/camunda-modeler-excel-import-plugin#107]
__Is your feature request related to a problem? Please describe.__

The plugin was built with C7 DMN diagrams in mind. [C8 support has to be added explicitly](https://github.com/pinussilvestrus/camunda-modeler-excel-import-plugin/blob/main/client/ExcelPlugin.js#L446) (`cloud-dmn`).

__Describe the solution you'd like__

Add C8 support.

__Describe alternatives you've considered__

/

__Additional context__

/

**Comment by PavanKumarV25** [comment]
Hi @pinussilvestrus 

can you please let me know how to make support  dmn for camunda 8 . now it is working only camunda 7. 

Thanks 
Pavan Kumar
