### ISSUE TITLE
Import cell content from Excel Sheets in quotation marks

### ISSUE THREAD

**Issue by KonstantinM13** [pinussilvestrus/camunda-modeler-excel-import-plugin#129]
I would like to import cells from my Excel Sheet in quotation marks or  choose certain columns which should be importet in quotation marks. Is there a way i can change that in the code? (excelHandler) since im not so familiar with js.

**Comment by KonstantinM13** [comment]
[example.xlsx](https://github.com/pinussilvestrus/camunda-modeler-excel-import-plugin/files/10849384/example.xlsx)

As you can see in the exmaple sheet, i want to leave for example the values in column A untouched and import them into dmn in quotation marks.

**Comment by pinussilvestrus** [comment]
Thanks for sharing!

What you could do is to update the [rule entry creation](https://github.com/pinussilvestrus/camunda-modeler-excel-import-plugin/issues) by adding quotes on string inputs

```js
getTypeRefs(row) === 'string' ? `"${text}"` : text
```

I'd like to not include this in this plugin, as the import should be no-magic.

**Comment by KonstantinM13** [comment]
Thanks for the fast reply!
Ich werde es mir umbauen sobald ich Zeit habe :)

**Comment by pinussilvestrus** [comment]
Viel Erfolg!
